sudo: false
language: python
python:
    - "2.7"
    - "3.4"

dist: precise
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - clang-format-3.8
install: 
  - pip install flake8
script:
  - cd $TRAVIS_BUILD_DIR
  - ./scripts/travis/run_clang_format_diff.sh master $TRAVIS_COMMIT
  - git checkout $TRAVIS_PULL_REQUEST_SHA
  - flake8 --config=flake8.cfg .
